version: "3.9"

services:
    django:
        build: .
        container_name: django
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
            {%- if cookiecutter.configuration.local_debugger.enabled == "True" %}
            - "3000:3000"
            {% endif %}
        environment:
            - DEBUG=true
            {%- if cookiecutter.configuration.xray.enabled == "True" %}
            - AWS_XRAY_SDK_ENABLED=false
            {% endif %}
            {%- if cookiecutter.caching.enabled == "True" %}
            - REDIS_URL=redis://redis:6379/0
            {% endif %}
            {%- if cookiecutter.database.enabled == "True" %}
            - DB_NAME=db
            - DB_USER=user
            - DB_PASSWORD=password
            {% endif %}
        {%- if cookiecutter.database.enabled == "True" or cookiecutter.caching.enabled == "True" %}
        depends_on:
            {%- if cookiecutter.database.type == "postgresql" %}
            postgres:
                condition: service_healthy
            {%- elif cookiecutter.database.type == "mysql" %}
            mysql:
                condition: service_healthy
            {%- endif %}
            {%- if cookiecutter.caching.enabled == "True" %}
            redis:
                condition: service_started
            {%- endif %}
      {%- endif %}
    {%- if cookiecutter.database.enabled == "True" %}
    {%- if cookiecutter.database.type == "postgresql" %}
    postgres:
        image: postgres
        container_name: postgres
        environment:
            - POSTGRES_DB=db                # "${DB_NAME}"
            - POSTGRES_USER=user            # "${DB_USER}"
            - POSTGRES_PASSWORD=password    # "${DB_PASSWORD}"
        ports:
            - "5432:5432"
        healthcheck:
            test:
              [
                  "CMD-SHELL",
                  "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
              ]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - pgdata:/var/lib/postgresql/data/
    {%- endif %}
    {%- if cookiecutter.database.type == "mysql" %}
    mysql:
        image: arm64v8/mysql
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db           # "${DB_NAME}"
            - MYSQL_USER=user             # "${DB_USER}"
            - MYSQL_PASSWORD=password     # "${DB_PASSWORD}"
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - mysqldata:/var/lib/mysql
    {%- endif %}
    {%- endif %}
    {%- if cookiecutter.caching.enabled == "True" %}
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
    {%- endif %}
    {%- if cookiecutter.configuration.xray == "True" %}
    xray:
        image: amazon/aws-xray-daemon
        container_name: xray
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_REGION=${AWS_REGION}
        ports:
            - "2000:2000"
            - "2000:2000/udp"
    {%- endif %}

{%- if cookiecutter.database.enabled == "True" %}
volumes:
    {%- if cookiecutter.database.type == "postgresql" %}
    pgdata:
    {%- endif %}
    {%- if cookiecutter.database.type == "mysql" %}
    mysqldata:
    {%- endif %}
{%- endif %}