name: ECS CDK Deployment

on:
  push:
    branches: [ main ]

env:
  RSA_PRIVATE_KEY: ${{ '{{' }} secrets.RSA_PRIVATE_KEY }}

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Load env
        run: |
          python setup/load_env.py

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ./

      - name: Install dependencies
        run: |
          cd cdk-deployment
          pip install -r requirements.txt
          npm install -g aws-cdk

      - name: Deploy stack
        run: |
          bash scripts/deploy.sh
