name: Deploy to EYK

on:
  push:
    branches:
    - main

concurrency:
  group: ${{ '{{' }} github.workflow }}-${{ '{{' }} github.ref }}
  cancel-in-progress: true

# Environment variables available to all jobs and steps in this workflow
env:
  EYK_STAGING_PRIVATE_KEY: ${{ '{{' }}secrets.EYK_STAGING_PRIVATE_KEY}}
  EYK_SSH_HOST: ${{ '{{' }}secrets.EYK_SSH_HOST}}
  EYK_APP_NAME: ${{ '{{' }}secrets.EYK_APP_NAME}}

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Load env
        run: | 
          python setup/load_env.py
      
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: ./

      # If you have setup eyk successfully on local machine
      # Then run -> `git remote show eyk` to get values of EYK_HOST and EYK_APP_NAME
      - name: Add EYK remote
        run: git remote add eyk "ssh://git@$EYK_SSH_HOST:2222/$EYK_APP_NAME.git"

      - name: Save secrets key and host
        run: |
          mkdir -p ~/.ssh/
          echo "$EYK_STAGING_PRIVATE_KEY" > ~/eyk_rsa
          chmod 600 ~/eyk_rsa
          ssh-keyscan -p 2222 -H "$EYK_SSH_HOST" >> ~/.ssh/known_hosts
      - name: Push to EYK
        run: |
          export GIT_SSH_COMMAND="ssh -i ~/eyk_rsa"
          git push eyk --force